openapi: 3.0.0
info:
  version: 1.0.0
  title: 'Nudr_DataRepository API OpenAPI file'
  description: 'Unified Data Repository Service'
externalDocs:
  description: 3GPP TS 29.504 V15.2.0; 5G System; Unified Data Repository Services; Stage 3
  url: 'http://www.3gpp.org/ftp/Specs/archive/29_series/29.504/'
servers:
  - description: API root
    url: '{apiRoot}/nudr-dr/v1'
    variables:
      apiRoot:
        default: https://example.com
security:
  - {}
  - oAuth2ClientCredentials:
      - nudr-dr

paths:
  /subscription-data/{ueId}/authentication-data:
    $ref: 'TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1authentication-data'
  /subscription-data/{ueId}/{servingPlmnId}/provisioned-data/am-data:
    $ref: 'TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1%7BservingPlmnId%7D~1provisioned-data~1am-data'
  /subscription-data/{ueId}/{servingPlmnId}/provisioned-data/smf-selection-subscription-data:
    $ref: 'TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1%7BservingPlmnId%7D~1provisioned-data~1smf-selection-subscription-data'
  /subscription-data/{ueId}/{servingPlmnId}/provisioned-data/sm-data:
    $ref: 'TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1%7BservingPlmnId%7D~1provisioned-data~1sm-data'
  /subscription-data/{ueId}/context-data/amf-3gpp-access:
    $ref: 'TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1context-data~1amf-3gpp-access'
  /subscription-data/{ueId}/context-data/amf-non-3gpp-access:
    $ref: 'TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1context-data~1amf-non-3gpp-access'
  /subscription-data/{ueId}/context-data/smf-registrations:
    $ref: 'TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1context-data~1smf-registrations'
  /subscription-data/{ueId}/context-data/smf-registrations/{pduSessionId}:
    $ref: 'TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1context-data~1smf-registrations~1%7BpduSessionId%7D'
  /subscription-data/{ueId}/operator-specific-data:
    $ref: 'TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1operator-specific-data'
  /subscription-data/{ueId}/context-data/smsf-3gpp-access:
    $ref: 'TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1context-data~1smsf-3gpp-access'
  /subscription-data/{ueId}/context-data/smsf-non-3gpp-access:
    $ref: 'TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1context-data~1smsf-non-3gpp-access'
  /subscription-data/{ueId}/{servingPlmnId}/provisioned-data/sms-mng-data:
    $ref: 'TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1%7BservingPlmnId%7D~1provisioned-data~1sms-mng-data'
  /subscription-data/{ueId}/{servingPlmnId}/provisioned-data/sms-data:
    $ref: 'TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1%7BservingPlmnId%7D~1provisioned-data~1sms-data'
  /subscription-data/{ueId}/pp-data:
    $ref: 'TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1pp-data'
  /subscription-data/{ueId}/context-data/ee-subscriptions:
    $ref: 'TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1context-data~1ee-subscriptions'
  /subscription-data/{ueId}/context-data/ee-subscriptions/{subsId}:
    $ref: 'TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1context-data~1ee-subscriptions~1%7BsubsId%7D'
  /subscription-data/{ueId}/context-data/sdm-subscriptions:
    $ref: 'TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1context-data~1sdm-subscriptions'
  /subscription-data/{ueId}/context-data/sdm-subscriptions/{subsId}:
    $ref: 'TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1context-data~1sdm-subscriptions~1%7BsubsId%7D'
  /subscription-data/subs-to-notify:
    $ref: 'TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1subs-to-notify'
  /subscription-data/subs-to-notify/{subsId}:
    $ref: 'TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1subs-to-notify~1%7BsubsId%7D'
  /subscription-data/{ueId}/{servingPlmnId}/provisioned-data/trace-data:
    $ref: 'TS29505_Subscription_Data.yaml#/paths/~1subscription-data~1%7BueId%7D~1%7BservingPlmnId%7D~1provisioned-data~1trace-data'
  /policy-data/{ueId}/am-data:
    $ref: 'TS29519_Policy_Data.yaml#/paths/~1policy-data~1%7BueId%7D~1am-data'
  /policy-data/{ueId}/ue-policy-set:
    $ref: 'TS29519_Policy_Data.yaml#/paths/~1policy-data~1%7BueId%7D~1ue-policy-set'
  /policy-data/{ueId}/sm-data:
    $ref: 'TS29519_Policy_Data.yaml#/paths/~1policy-data~1%7BueId%7D~1sm-data'
  /policy-data/{ueId}/sm-data/{usageMonId}:
    $ref: 'TS29519_Policy_Data.yaml#/paths/~1policy-data~1%7BueId%7D~1sm-data~1%7BusageMonId%7D'
  /policy-data/sponsor-connectivity-data/{sponsorId}:
    $ref: 'TS29519_Policy_Data.yaml#/paths/~1policy-data~1sponsor-connectivity-data~1%7BsponsorId%7D'
  /policy-data/bdt-data:
    $ref: 'TS29519_Policy_Data.yaml#/paths/~1policy-data~1bdt-data'
  /policy-data/bdt-data/{bdtReferenceId}:
    $ref: 'TS29519_Policy_Data.yaml#/paths/~1policy-data~1bdt-data~1%7BbdtReferenceId%7D'
  /policy-data/subs-to-notify:
    $ref: 'TS29519_Policy_Data.yaml#/paths/~1policy-data~1subs-to-notify'
  /policy-data/subs-to-notify/{subsId}:
    $ref: 'TS29519_Policy_Data.yaml#/paths/~1policy-data~1subs-to-notify~1%7BsubsId%7D'
  /policy-data/{ueId}/operator-specific-data:
    $ref: 'TS29519_Policy_Data.yaml#/paths/~1policy-data~1%7BueId%7D~1operator-specific-data'
  /application-data/pfds:
    $ref: 'TS29519_Application_Data.yaml#/paths/~1application-data~1pfds'
  /application-data/pfds/{application-identifier}:
    $ref: 'TS29519_Application_Data.yaml#/paths/~1application-data~1pfds~1%7Bapplication-identifier%7D'
  /application-data/influenceData:
    $ref: 'TS29519_Application_Data.yaml#/paths/~1application-data~1influenceData'
  /application-data/influenceData/{afServiceId}:
    $ref: 'TS29519_Application_Data.yaml#/paths/~1application-data~1influenceData~1%7BafServiceId%7D'
  /application-data/influenceData/subscriptions:
    $ref: 'TS29519_Application_Data.yaml#/paths/~1application-data~1influenceData~1subscriptions'
  /application-data/influenceData/subscriptions/{subscriptionId}:
    $ref: 'TS29519_Application_Data.yaml#/paths/~1application-data~1influenceData~1subscriptions~1%7BsubscriptionId%7D'
  /exposure-data/{ueId}/access-and-mobility-data:
    $ref: 'TS29519_Exposure_Data.yaml#/paths/~1exposure-data~1%7BueId%7D~1access-and-mobility-data'
  /exposure-data/{ueId}/session-management-data:
    $ref: 'TS29519_Exposure_Data.yaml#/paths/~1exposure-data~1%7BueId%7D~1session-management-data'
  /exposure-data/{ueId}/session-management-data/{pduSessionId}:
    $ref: 'TS29519_Exposure_Data.yaml#/paths/~1exposure-data~1%7BueId%7D~1session-management-data~1%7BpduSessionId%7D'
  /exposure-data/subs-to-notify:
    $ref: 'TS29519_Exposure_Data.yaml#/paths/~1exposure-data~1subs-to-notify'
  /exposure-data/subs-to-notify/{subId}:
    $ref: 'TS29519_Exposure_Data.yaml#/paths/~1exposure-data~1subs-to-notify~1%7BsubId%7D'
components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows: 
        clientCredentials: 
          tokenUrl: '{nrfApiRoot}/oauth2/token'
          scopes: 
            nudr-dr: Access to the Nudr_DataRepository API

