openapi: 3.0.0
info:
  version: 1.2.0-alpha.2
  title: AUSF API
  description: |
    AUSF UE Authentication Service.
    © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.

externalDocs:
  description: 3GPP TS 29.509 V17.3.0; 5G System; 3GPP TS Authentication Server services.
  url: 'http://www.3gpp.org/ftp/Specs/archive/29_series/29.509'

servers:
  - url: '{apiRoot}/nausf-auth/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in clause clause 4.4 of 3GPP TS 29.501.

security:
  - {}
  - oAuth2ClientCredentials:
      - nausf-auth

paths:
  /ue-authentications:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticationInfo'
        required: true
      responses:
        '201':
          description: UEAuthenticationCtx
          content:
            application/3gppHal+json:
              schema:
                $ref: '#/components/schemas/UEAuthenticationCtx'
          headers:
            Location:
              description: 'Contains the URI of the newly created resource according to the structure: {apiRoot}/nausf-auth/v1/ue-authentications/{authCtxId}'
              required: true
              schema:
                type: string
        '307':
          description: temporary redirect
          headers:
            Location:
              description: 'An alternative URI of the resource located on an alternative service instance within the same AUSF or AUSF (service) set '
              required: true
              schema:
                type: string
            3gpp-Sbi-Target-Nf-Id:
              description: 'Identifier of target AUSF (service) instance towards which the request is redirected'
              schema:
                type: string
        '308':
          description: permanent redirect
          headers:
            Location:
              description: 'An alternative URI of the resource located on an alternative service instance within the same AUSF or AUSF (service) set '
              required: true
              schema:
                type: string
            3gpp-Sbi-Target-Nf-Id:
              description: 'Identifier of target AUSF (service) instance towards which the request is redirected'
              schema:
                type: string

        '400':
          description: Bad Request from the AMF
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
        '403':
          description: Forbidden due to serving network not authorized
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
        '404':
          description: User does not exist in the HPLMN
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
        '501':
          description: Received protection scheme is not supported by HPLMN
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'

  /ue-authentications/deregister:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeregistrationInfo'
        required: true
      responses:
        '204':
          description: Expected response to a successful removal of security context
        '307':
          description: temporary redirect
          headers:
            Location:
              description: 'An alternative URI of the resource located on an alternative service instance within the same AUSF or AUSF (service) set '
              required: true
              schema:
                type: string
            3gpp-Sbi-Target-Nf-Id:
              description: 'Identifier of target AUSF (service) instance towards which the request is redirected'
              schema:
                type: string
        '308':
          description: permanent redirect
          headers:
            Location:
              description: 'An alternative URI of the resource located on an alternative service instance within the same AUSF or AUSF (service) set '
              required: true
              schema:
                type: string
            3gpp-Sbi-Target-Nf-Id:
              description: 'Identifier of target AUSF (service) instance towards which the request is redirected'
              schema:
                type: string

        '404':
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'

  /ue-authentications/{authCtxId}/5g-aka-confirmation:
    put:
      parameters:
        - name: authCtxId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfirmationData'
      responses:
        '200':
          description: Request processed (EAP success or Failure)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfirmationDataResponse'
        '307':
          description: temporary redirect
          headers:
            Location:
              description: 'An alternative URI of the resource located on an alternative service instance within the same AUSF or AUSF (service) set '
              required: true
              schema:
                type: string
            3gpp-Sbi-Target-Nf-Id:
              description: 'Identifier of target AUSF (service) instance towards which the request is redirected'
              schema:
                type: string
        '308':
          description: permanent redirect
          headers:
            Location:
              description: 'An alternative URI of the resource located on an alternative service instance within the same AUSF or AUSF (service) set '
              required: true
              schema:
                type: string
            3gpp-Sbi-Target-Nf-Id:
              description: 'Identifier of target AUSF (service) instance towards which the request is redirected'
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
    delete:
      summary: Deletes the authentication result in the UDM
      operationId: Delete5gAkaAuthenticationResult
      tags:
        - Authentication Result Deletion
      parameters:
        - name: authCtxId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Expected response to a successful authentication result removal
        '307':
          description: temporary redirect
          headers:
            Location:
              description: 'An alternative URI of the resource located on an alternative service instance within the same AUSF or AUSF (service) set '
              required: true
              schema:
                type: string
            3gpp-Sbi-Target-Nf-Id:
              description: 'Identifier of target AUSF (service) instance towards which the request is redirected'
              schema:
                type: string
        '308':
          description: permanent redirect
          headers:
            Location:
              description: 'An alternative URI of the resource located on an alternative service instance within the same AUSF or AUSF (service) set '
              required: true
              schema:
                type: string
            3gpp-Sbi-Target-Nf-Id:
              description: 'Identifier of target AUSF (service) instance towards which the request is redirected'
              schema:
                type: string

        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '404':
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '500':
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'

  /ue-authentications/{authCtxId}/eap-session:
    post:
      operationId: EapAuthMethod
      parameters:
        - name: authCtxId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EapSession'
      responses:
        '200':
          description: Use to handle or close the EAP session
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EapSession'

            application/3gppHal+json:
              schema:
                type: object
                properties:
                  eapPayload:
                    $ref: '#/components/schemas/EapPayload'
                  _links:
                    type: object
                    description: 'URI : /{eapSessionUri}, a map(list of key-value pairs) where member serves as key'
                    additionalProperties:
                      $ref: 'TS29571_CommonData.yaml#/components/schemas/LinksValueSchema'
                    minProperties: 1
                required:
                  - eapPayload
                  - _links
        '307':
          description: temporary redirect
          headers:
            Location:
              description: 'An alternative URI of the resource located on an alternative service instance within the same AUSF or AUSF (service) set '
              required: true
              schema:
                type: string
            3gpp-Sbi-Target-Nf-Id:
              description: 'Identifier of target AUSF (service) instance towards which the request is redirected'
              schema:
                type: string
        '308':
          description: permanent redirect
          headers:
            Location:
              description: 'An alternative URI of the resource located on an alternative service instance within the same AUSF or AUSF (service) set '
              required: true
              schema:
                type: string
            3gpp-Sbi-Target-Nf-Id:
              description: 'Identifier of target AUSF (service) instance towards which the request is redirected'
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'

    delete:
      summary: Deletes the authentication result in the UDM
      operationId: DeleteEapAuthenticationResult
      tags:
        - Authentication Result Deletion
      parameters:
        - name: authCtxId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Expected response to a successful authentication result removal
        '307':
          description: temporary redirect
          headers:
            Location:
              description: 'An alternative URI of the resource located on an alternative service instance within the same AUSF or AUSF (service) set '
              required: true
              schema:
                type: string
            3gpp-Sbi-Target-Nf-Id:
              description: 'Identifier of target AUSF (service) instance towards which the request is redirected'
              schema:
                type: string
        '308':
          description: permanent redirect
          headers:
            Location:
              description: 'An alternative URI of the resource located on an alternative service instance within the same AUSF or AUSF (service) set '
              required: true
              schema:
                type: string
            3gpp-Sbi-Target-Nf-Id:
              description: 'Identifier of target AUSF (service) instance towards which the request is redirected'
              schema:
                type: string
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '404':
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '500':
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'

  /rg-authentications:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RgAuthenticationInfo'
        required: true
      responses:
        '201':
          description: RgAuthCtx
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RgAuthCtx'
          headers:
            Location:
              description: 'Contains the URI of the newly created resource according to the structure: {apiRoot}/nausf-auth/v1/rg-authentications/{authCtxId}'
              required: true
              schema:
                type: string
        '307':
          description: temporary redirect
          headers:
            Location:
              description: 'An alternative URI of the resource located on an alternative service instance within the same AUSF or AUSF (service) set '
              required: true
              schema:
                type: string
            3gpp-Sbi-Target-Nf-Id:
              description: 'Identifier of target AUSF (service) instance towards which the request is redirected'
              schema:
                type: string
        '308':
          description: permanent redirect
          headers:
            Location:
              description: 'An alternative URI of the resource located on an alternative service instance within the same AUSF or AUSF (service) set '
              required: true
              schema:
                type: string
            3gpp-Sbi-Target-Nf-Id:
              description: 'Identifier of target AUSF (service) instance towards which the request is redirected'
              schema:
                type: string
        '403':
          description: The UE is not allowed to be authenticated
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
        '400':
          description: Bad Request from the AMF
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
        '404':
          description: User does not exist in the HPLMN
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'

components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{nrfApiRoot}/oauth2/token'
          scopes:
            nausf-auth: Access to Nausf_UEAuthentication API

  schemas:
