openapi: 3.0.0
info:
  title: Data Collection and Reporting Common Data Types
  version: 1.0.0
  description: |
    Data Collection and Reporting Common Data Types
    © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.
tags:
  - name: Data Collection and Reporting Common Data Types
    description: 'Data Collection and Reporting: Common Data Types'
externalDocs:
  description: 'TS 26.532 V17.0.0; Data Collection and Reporting; Protocols and Formats'
  url: 'https://www.3gpp.org/ftp/Specs/archive/26_series/26.532/'
paths: {}
components:
  schemas:
    #################################
    # Clause 5.4.1: Simple data types
    #################################

    #####################################
    # Clause 5.4.2: Structured data types
    #####################################

    #####################################
    # Clause 5.4.3: Enumerated data types
    #####################################

    DataCollectionClientType:
      anyOf:
        - type: string
          enum: [DIRECT, INDIRECT, APPLICATION_SERVER]
        - type: string
          description: >
            This string provides forward-compatibility with future
            extensions to the enumeration but is not used to encode
            content defined in the present version of this API.
